### PR TITLE
Add Prof. Edelman's notebooks

### PR DESCRIPTION
**Pull request by tkoolen**

### CODE REVIEW

**Comment by tkoolen** [comment]
Thanks, Robin.

**Comment by tkoolen** [comment]
The GCC call results in trouble in the julia is fast notebook.

**Comment by rdeits** [comment]
Yeah, I see that on Travis. It does work on my machine, at least.

**Comment by rdeits** [comment]
Wow, MacroTools pushed a new patch that breaks....literally everything. Any package that depends on it now segfaults during precompile: https://github.com/JuliaLang/METADATA.jl/pull/7903

I've updated our REQUIRE to make sure we don't get that version.

**Pull request merged**
