### PR TITLE
add JuMP demo and appropriate requirements

### PR DESCRIPTION
**Pull request by rdeits**
@tkoolen I'm brining in GR for plotting because PyPlot is just too slow for the animations I want to do for JuMP. Also GR just looks better. 

I also had a surprisingly hard time finding a free QP solver for JuMP, so I settled on Ipopt.

### CODE REVIEW

**Comment by rdeits** [comment]
Hm, maybe not. Ipopt requires gfortran but doesn't install it for you. Maybe I can get away with something lighter...

**Comment by tkoolen** [comment]
Worst case, just use gurobi and only run that notebook if gurobi is found (rough check could be `isdir(Pkg.dir("Gurobi"))`.

**Comment by rdeits** [comment]
Yeah, that's probably fine.

**Comment by rdeits** [comment]
Ok, yeah, the ipopt build is way too long. I'll just test this notebook myself.

**Comment by rdeits** [comment]
I'm getting unreliable weird failures in certain cells, like this:

```
CellExecutionError: An error occurred while executing the following cell:
------------------
# add a method to Base.flipsign and eps for SymPy. TODO: SymPy PR
Base.flipsign(sym::Sym, sign::Number) = sign > 0 ? sym : -sym;
Base.eps(::Type{SymPy.Sym}) = zero(Sym)
------------------
LoadError: UndefVarError: Sym not defined
```

I'm going to ignore it for now because it's not actually a problem with the notebooks.

**Comment by tkoolen** [comment]
Hmm, that's strange. There's a `using SymPy` in the cell above that, so since that ran without error I don't see how this could happen...

**Comment by rdeits** [comment]
Yeah, it seems to be a random occurrence.

**Pull request merged**
